baseURL = "/"
languageCode = "en-us"
paginate = "5"
title = "Dennis Eugene Stepp, Jr."
theme = "mainroad"
#disqusShortname = "dennisstepp" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-106319098-1" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Dennis Eugene Stepp, Jr."
    bio = "I am a software developer in Knoxville, TN. I'm also a game/web developer with Unibear Studio, and stage manager/web developer with the Earl Park Fall Festival Foundation. My interests include: process and workflow optimization, automation, JAMstack technologies, software architecture, object oriented languages, and game development. I also collect retro PC/console video games, dabble in gardening and woodworking. I have a passion for craft beer, especially while playing recreational ice hockey."
    avatar = "img/profile.png"

[Params]
    subpage1 = "Posts"
    subpage2 = "About Me"
    subtitle = "Sharpen Your Axe" # Subtitle of your site
    description = "The journey of sharping technical and soft skills as a software developer." # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_facebook = "dj.stepp.7"
    social_twitter = "destepp"
    social_linkedin = "dennisstepp"
    social_github = "destepp11"
    social_email = "destepp11@gmail.com"